# Generated by Django 6.0.4 on 2026-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='heleket_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
