# Generated by Django 6.0.4 on 2026-04-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address1_order_address_and_more'),
    ]

    operations = [
    ]
