# Generated by Django 6.0.4 on 2026-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_brand_from_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID корзины'),
        ),
    ]
